### ISSUE TITLE
Develop API for receiving an InputStream and output a JSON

### ISSUE THREAD

**Issue by alexmbraga** [eubr-atmosphere/PRIVAaaS#12]
- This is a new Java API for the privacy component PRIVAaaS
-  Receive an InputStream containing CVS-formatted data
- Output a JSON containing obfuscated/anonimized data
- ARX already has a API for handling CSV data from an InputStream
- The transformation to JSON saves time and reduces the need for data conversion outside the component.

**Comment by mrmassis** [comment]
Finished and commited.
